name: Count vehicles
on:
  schedule:
    - cron: "0 1-5 * * *"

jobs:
  ssh-key-action:
    name: Count vehicles
    runs-on: ubuntu-latest
    steps:
      - name: repo checkout
        uses: actions/checkout@master
        
      - name: SSH -> installing ssh key
        uses: shimataro/ssh-key-action@v2.5.0
        with:
          key: ${{ secrets.PRIVATE_KEY }} 
          known_hosts: unnecessary
          
      - name: SSH -> running video recorder script
        uses: fifsky/ssh-action@master
        with:
          command: |
            sshpass -p ${{ secrets.PASSWORD }} ssh -p 22 ${{ secrets.USER }}@${{ secrets.WIN_IP }} 'powershell.exe -Command "C:/Users/pi/git/pte-yolo-node/venv/Scripts/python.exe C:/Users/pi/git/pte-yolo-node/main.py"' &
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.PRIVATE_KEY}}