name: Deploying Python code
on:
  - push

jobs:
  ssh-key-action:
    name: Deploying Python code
    runs-on: ubuntu-latest
    steps:
      - name: repo checkout
        uses: actions/checkout@master
        
      - name: SSH -> installing ssh key
        uses: shimataro/ssh-key-action@v2.5.1
        with:
          key: ${{ secrets.PRIVATE_KEY }} 
          known_hosts: unnecessary

      - name: Fedora Server -> deploying project
        uses: fifsky/ssh-action@master
        with:
          command: |
            ssh -p 22 ${{ secrets.USER }}@${{ secrets.WIN_IP }} "cd /home/pi/git/pte-yolo-node; git fetch --all; git reset --hard origin/main"
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.PRIVATE_KEY}}
