name: Record video
on:
  schedule:
    - cron: "0 7 * * *"

jobs:
  ssh-key-action:
    name: Record video
    if: ${{ false }}
    runs-on: ubuntu-latest
    steps:
      - name: repo checkout
        uses: actions/checkout@master
        
      - name: SSH -> installing ssh key
        uses: shimataro/ssh-key-action@v2.5.0
        with:
          key: ${{ secrets.PRIVATE_KEY }} 
          known_hosts: unnecessary
          
      - name: SSH -> adding remote to known hosts
        # port: 12399
        run: ssh-keyscan -p ${{ secrets.PORT }} -H ${{ secrets.HOST }}  >> ~/.ssh/known_hosts

      - name: SSH -> running video recorder script
        uses: fifsky/ssh-action@master
        with:
          command: |
            python3 /home/pi/scripts/record-video-python.py
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.PRIVATE_KEY}}