name: upload

on:
  - push

jobs:
  upload:
    name: Upload
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@master

      - name: Upload file via SSH
        uses: nicklasfrahm/scp-action@main
        with:
          direction: "upload"
          host: "4.tcp.eu.ngrok.io"
          port: "12399"
          username: "pi"
          insecure_ignore_fingerprint: "true"
          insecure_password: "@Rduino"
          source: "./a.txt"
          target: "/home/pi/a.txt"
