name: upload

on:
  - push

jobs:
  upload:
    name: Upload
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@master

      - name: Upload file via SSH
        uses: nicklasfrahm/scp-action@main
        with:
          direction: "upload"
          host: ${{ secrets.HOST }}
          port: "12399"
          username: ${{ secrets.USER }}
          fingerprint: ${{ secrets.HOST_FINGERPRINT }}
          key: ${{ secrets.PRIVATE_KEY }}
          source: "./cam-record.sh"
          target: "/home/pi/scripts/cam-record.sh"
