name: upload

on:
  - push

jobs:
  upload:
    name: Upload
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@master

      - name: Upload file via SSH
        uses: nicklasfrahm/scp-action@main
        with:
          direction: "upload"
          host: ${{ secrets.HOST }}
          port: "12399"
          username: ${{ secrets.USER }}
          insecure_ignore_fingerprint: "true"
          insecure_password: ${{ secrets.PASSWORD }}
          source: "./cam-record.sh"
          target: "/home/pi/scripts/cam-record.sh"
      
      - name: SSH command runner
        uses: fifsky/ssh-action@master
        with:
          # Command to execute on the remote server.
          command: touch /home/pi/ssh-works.txt
          # Hostname or IP address of the server.
          host: ${{ secrets.HOST }}
          # Username for authentication.
          user: ${{ secrets.USER }}
          # Port number of the server.
          port: 12399
          pass: ${{ secrets.PASSWORD }}
          
      - name: Run shell script
        run: |
          ls -a
          pwd
