name: Deploying shell scripts

on:
  - push

jobs:
  ssh-key-action:
    name: Deploying shell scripts
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@master
        
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2.5.0
        with:
          key: ${{ secrets.PRIVATE_KEY }} 
          known_hosts: unnecessary
          
      - name: Adding Known Hosts
        # port: 12399
        run: ssh-keyscan -p ${{ secrets.PORT }} -H ${{ secrets.HOST }}  >> ~/.ssh/known_hosts

      - name: SSH command runner
        uses: fifsky/ssh-action@master
        with:
          command: touch /home/pi/ssh-works-YAYYY.txt
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.PRIVATE_KEY}}
        
      - name: SCP upload -> record-video.sh
        uses: nicklasfrahm/scp-action@main
        with:
          direction: "upload"
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USER }}
          insecure_ignore_fingerprint: "true"
          fingerprint: ${{ secrets.FINGERPRINT }}
          key: ${{ secrets.PRIVATE_KEY }}
          source: "./record-video.sh"
          target: "/home/pi/scripts/record-video.sh"

      - name: SCP upload -> rename-split-files.sh
        uses: nicklasfrahm/scp-action@main
        with:
          direction: "upload"
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USER }}
          insecure_ignore_fingerprint: "true"
          fingerprint: ${{ secrets.FINGERPRINT }}
          key: ${{ secrets.PRIVATE_KEY }}
          source: "./rename-split-files.sh"
          target: "/home/pi/scripts/rename-split-files.sh"
          
